### PR TITLE
Highlighting improvements

### LINKED ISSUE #118: Do not highlight whitespace
Recently I wrote:

> I think that most of the changes in the "known good" files come from tokenizing whitespace, which seems entirely harmless.

This is untrue. We should not tokenize whitespace, as was done in #111.

This is because although whitespace is not colored in VS code, if you use a theme such as Abyss or Monokai which uses underlines, the whitespace will be underlined, which is not good.

We can either match a fixed amount of whitespace (which is brittle; we should probably avoid that), use programmatic highlighting instead of declarative highlighting (see `highlight.ts`), or do some trick with conditionally nested groups of patterns. This third option is what we do in order to apply the correct target language highlighter according to the target declaration, and I think I prefer it.

### PR DESCRIPTION
**Pull request by petervdonovan**
This makes adjustments that may improve the alignment of the highlighter with the equals initializer syntax.

It also makes small improvements to the highlighter.

Fixes #118. Whitespace is still highlighted in files that have multiple spaces when just one would suffice, but at least all well-formatted files are highlighted correctly. I think it is OK to make bad files look bad.

### CODE REVIEW

**Comment by lhstrh** [comment]
Amazing! We're getting ahead of @oowekyala now :-D

**Comment by lhstrh** [comment]
I take it that this no longer depends on the merging of the above mentioned PR?

**Comment by petervdonovan** [comment]
Well, I tested these changes on the currently tracked `lingua-franca` submodule, and it highlighted the tests just fine.

**Review by lhstrh — APPROVED** [review]
Great! Let's merge!

**Pull request merged**
